### PR TITLE
Add ability to deploy to dedicated server

### PR DESCRIPTION
**Pull request by patcon**
//cc @sylus

From #21:

> 4) I would love if we adapted and integrated the https://github.com/wch/vagrant-ec2-r repo so can do a simply deployment to ec2 without needing chef server. I tested it myself and worked great with their custom cookbooks. Looking at the code it only parses the run_list and converts to json (runs chef -c .... -j dna.json) but would be great to add roles etc. This could be used for users who don't have a capable enough local computer. If we included a step by step on running on a m1.small server could help alot!

That repo is a cool effort hadn't seen! But thinking [knife-solo](https://github.com/matschaffer/knife-solo) or [pocketknife](https://github.com/igal/pocketknife) might be the better approaches? (I've already used knife-solo in our [Inception project](https://github.com/myplanetdigital/inception), and so I lean toward that.)

### CODE REVIEW

**Comment by skottler** [comment]
Who said my name?!

I think that Ariadne actually extends to production servers quite easily. The cookbooks are going to be the same, just with different deployment targets. +1 to @patcon's suggestion of knife-ec2. Maybe some basic firewall rules should ship, too?

**Comment by patcon** [comment]
Hm. Ok, so if it doesn't worry you, then it doesn't worry me :)

Good call on the firewall rules. I'll create an issue. And was learning toward knife-solo. Does knife-ec2 play nice if you're just using chef-solo?

**Comment by nerdcorenet** [comment]
These scripts are intended to facilitate a quick and easy installation of Chef-Solo onto an Amazon EC2 server.

http://www.opinionatedprogrammer.com/2011/06/chef-solo-tutorial-managing-a-single-server-with-chef/

Do you suppose this method could be adapted to use Ariadne's cookbooks and setup processes to spin up deployment instances as well as developments instances?

**Comment by patcon** [comment]
Hm. It might be doable, but it looks to do most of the things that knife-solo does, except knife-solo is a community-supported tool. Have you checked out knife-solo and still think that tutorial's method is preferable?

**Comment by nerdcorenet** [comment]
I certainly would like to keep with something actively maintained such as knife-solo. I found the README to be weak, though. I'm not sure how to proceed with knife-solo and therefore how I would use it to deploy Ariadne.

**Comment by patcon** [comment]
Hm... this will likely come into play, as ariadne depends on agent forwarding that vagrant does:
matschaffer/knife-solo#11

**Comment by patcon** [comment]
Doesn't yet make it through the chef run, but here are the instructions so far:
https://github.com/myplanetdigital/ariadne/tree/44-knife-solo#deploying-wip

Basically still need to clean up some of the roles and recipes that make assumptions about `vagrant` users and stuff like that. Will also likely need to move local-specific settings back in `Vagrantfile` json array too

I need to wrap up for the day, but currently stalling with this:

```
[2012-10-03T20:53:14+00:00] FATAL: ArgumentError: bash_profile[drupalcs-alias] (phpcs::drupal_standard line 18) had an error: ArgumentError: user vagrant doesn't exist
Run finished in 354.069475 seconds
```

Might be resolved by taking this discussion into account:
https://drupal.org/node/1774268

**Comment by mgifford** [comment]
Great to see this moving along. There are just so many ways to sorta do this kinda thing, but after trying a bunch of them (with limited knowledge of Ruby or Chef)....  It's been frustrating.

**Comment by skottler** [comment]
Most (all?) vagrant baseboxes have the 'vagrant' user already created so it exists outside of chef. @patcon I think it makes the most sense to just add a user resource to make this platform agnostic.

**Comment by patcon** [comment]
Working on this now.

TODO:
- [ ] Figure out good/easy way to allow root/root mysql password on vagrant but not for remote server
- [ ] basic firewall rules (ref #59)

EDIT: Spinning these off into other issues (referenced below)

**Pull request merged**
