### PR TITLE
Follow-up on issue #10: as a user, I should be able to use non-github repositories

### PR DESCRIPTION
**Pull request by mparker17**
Here is my pull request.

Sorry about the confusion. :P

### CODE REVIEW

**Comment by mparker17** [comment]
What happened there? Why did Github include all of those commits you made?

**Comment by mparker17** [comment]
Oh... that's why... I was on the wrong branch. :(

**Comment by mparker17** [comment]
For some reason, this was branched from develop on a clean local copy; but when I actually go to do the pull request, it won't let me request a merge into the develop branch!

So I'm re-opening this.

**Comment by patcon** [comment]
Hm. Already added this, so closing. thanks matt!

**Pull request closed without merging**
