### PR TITLE
Cleanup readme

### PR DESCRIPTION
**Pull request by mparker17**
I improved the README file by:
- reducing repetition
- simplifying instructions and making them very clear
- splitting the stuff at the end of the file into various sections
- putting all related information into one place

### CODE REVIEW

**Comment by mparker17** [comment]
Note this does not contain the changes to the README in GH-60. Depending on which pull request you merge first, I'll take care of resolving conflicts in the other.

**Comment by patcon** [comment]
THIS. IS. AWESOME.

Just need some time to look over, and I'll try to do that tonight :)

**Comment by sylus** [comment]
Really like the new README very concise :)

**Comment by patcon** [comment]
Overall, this is effing sahweet Matt. There are a couple minor nitpicky changes that I might revert (mostly terms and markdown style), but I'm just going to merge and deal with that later. Thanks man!

**Pull request merged**
