### PR TITLE
Add support and configuration for Strainer

### PR DESCRIPTION
**Pull request by sethvargo**
Here ya go!

### CODE REVIEW

**Comment by sethvargo** [comment]
You'll definitely want to update your `.travis.yml` file to use strainer, but I didn't want to screw with CI on this branch.

**Comment by patcon** [comment]
By the power vested in me by the state of New York, I declare that you're _fucking awesome_.

Thanks seth :) reviewing soon

**Comment by patcon** [comment]
haha saw your error handling on multiple paths :) I'll work on at least having to carry through and warn, as otherwise I'll need to have travis rerun for each `COOKBOOK=blah` variable instead of doing a single run with the whole `COOKBOOKS="ariadne varnish apache2 blah blah"`

But thanks. This got me past the part I was getting frustrated with :)

Hopefully a PR will be forthcoming soon. I'll keep this open to remind me on my end

**Comment by sethvargo** [comment]
That's how I have Jenkins setup to run our builds. Each build runs against the same repository, but runs based on a $COOKCOOK environment variable. 

Also note, Colanderfile can be cookbook specific. Just add a Colanderfile to that cookbook dir and it will take precedence

**Comment by patcon** [comment]
Ah gotcha. I'd be more likely to go the COOKBOOK envvar route if this was private, but I'm running on travis, so I want to be a good open-source citizen and take as little VM resources as possible :) (Probably better ways to do that mind you...)

**Comment by patcon** [comment]
holy eff. just looked over my other msgs. i promise, i don't normally need this many smiley face to interact with someone...

yeesh, how embarrassing...

**Comment by sethvargo** [comment]
Haha you're just in a good mood today :-p

**Comment by sethvargo** [comment]
@patcon I'm going to close this if you're okay with it. Trying to reduce my long-running pull requests.

**Comment by patcon** [comment]
For sure man, thanks for everything! I'm just getting back into this project again this week

**Comment by patcon** [comment]
Hm. Actually, this might be a poor side-effect of the long-running pull request feature. I'm totally going to forget about this since it's closed...

cc @rick

**Comment by sethvargo** [comment]
@patcon you can totally reopen if you're still using it. I just thought you were finished.

**Comment by patcon** [comment]
Ah ok, thought it was making your dashboard messy. Still not merged but haven't ruled it out :)

**Comment by rick** [comment]
Wrong @rick, I think.  :-)

**Comment by sethvargo** [comment]
@patcon the interface for Strainer has changed significantly and this PR is no longer valid :frowning:. Would you like me to re-implement?

**Comment by patcon** [comment]
You're awesome for asking, but no worries :)

**Pull request closed without merging**
